# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
# NOTE: For ngrok usage, update application_url and redirect_urls below with your ngrok URL
# When using 'shopify app dev', URLs are updated automatically (see automatically_update_urls_on_dev)

client_id = "f76e6856eec79af311a1df6c950105a7"
name = "nudge"
application_url = "https://dimple-hystricomorphic-long.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://dimple-hystricomorphic-long.ngrok-free.dev/api/auth/callback" ]
